params:
  fq_encoding: "sanger"
  begin: "calling"
  samples: "samples.tsv"

  simulate:
    do: False
    threads: 8

  raw:
    threads: 8
    check_paired: True
    save_reads: True
    fastqc:
      do: False

  qcreport:
    do: True
    seqkit:
      threads: 4


output:
  simulate: "results/00.simulate"
  raw: "results/00.raw"


envs:
  simulate: "envs/simulate.yaml"
  raw: "envs/raw.yaml"
  fastqc: "envs/fastqc.yaml"
  multiqc: "envs/multiqc.yaml"